name: 'Zephyr SDK'
description: 'download, install and cache zephyr SDK'
inputs:
  url:
    description: 'Where to download the SDK from'
    required: true
  cache-name:
    description: 'cache key for the installed SDK'
    required: true
  toolchains:
    description: 'comma separated list of toolchains to install.'
    required: false
    default: 'all'
runs:
  using: 'node16'
  main: 'dist/index.js'
